INSERT INTO roles (name)
SELECT * FROM (SELECT 'ROLE_ADMIN') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_ADMIN'
) LIMIT 1;

INSERT INTO roles (name)
SELECT * FROM (SELECT 'ROLE_STUDENT') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_STUDENT'
) LIMIT 1;

INSERT INTO roles (name)
SELECT * FROM (SELECT 'ROLE_PROFESSOR') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM roles WHERE name = 'ROLE_PROFESSOR'
) LIMIT 1;